# Generated by Django 6.0.1 on 2026-02-22 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0007_alter_book_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
