# Generated by Django 6.0.1 on 2026-02-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_add_book', 'can add new book'), ('can_change_book', 'can change new book'), ('can_view_book', 'can view new book'), ('can_delete_book', 'can delete new book')]},
        ),
    ]
