# Generated by Django 6.0.1 on 2026-02-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0006_alter_book_options_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'can add new book'), ('can_change_book', 'can change new book'), ('can_delete_book', 'can delete new book')]},
        ),
    ]
