# Generated by Django 6.0.3 on 2026-03-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_Year',
            new_name='publication_year',
        ),
    ]
